[package]
name = "rustfstest"
version = "0.1.0"
edition = "2021"
authors = ["hukeyang <hky1999@buaa.edu.cn>"]
description = "A Rust-based simple fs benchmark, refer to https://github.com/LLNL/mdtest.git"

[target.'cfg(target_os = "linux")'.dependencies]
clap = { version = "4.1", features = ["derive"], optional = true }


[dependencies]
cfg-if = "1.0.0"

[features]
default = ["std"]
std = ["dep:clap"]
alloc = []
